name: elmiko's notes
title: elmiko's notes
description: Notes from the front lines of development
url: https://notes.elmiko.dev
markdown: kramdown
highlighter: rouge
paginate: 1
safe: true
lsi: false
